# Brute force

In [1]:
import numpy as np
fname = 'input'
s = open(fname,'r').read().replace("| ","")
symbols = [line.split(" ") for line in s.split("\n")]
symbols_len = [[len(word) for word in line] for line in symbols]

values = [line[10:] for line in symbols_len]

values


[[5, 5, 2, 4],
 [7, 4, 5, 6],
 [6, 5, 6, 5],
 [5, 3, 3, 6],
 [5, 6, 3, 4],
 [6, 6, 5, 3],
 [2, 6, 7, 3],
 [5, 7, 5, 3],
 [2, 2, 6, 3],
 [7, 6, 4, 4],
 [3, 6, 2, 6],
 [3, 5, 6, 6],
 [3, 3, 6, 5],
 [2, 3, 5, 6],
 [5, 5, 4, 3],
 [4, 3, 5, 3],
 [5, 4, 4, 6],
 [4, 7, 6, 4],
 [3, 2, 3, 5],
 [5, 7, 2, 5],
 [5, 4, 5, 2],
 [6, 6, 6, 7],
 [5, 3, 6, 5],
 [2, 6, 3, 6],
 [6, 6, 4, 2],
 [2, 6, 6, 6],
 [4, 2, 3, 7],
 [5, 7, 7, 5],
 [2, 6, 4, 2],
 [7, 2, 7, 4],
 [6, 6, 7, 4],
 [6, 6, 4, 2],
 [6, 5, 5, 2],
 [4, 5, 3, 7],
 [6, 4, 6, 2],
 [7, 5, 3, 5],
 [6, 5, 6, 6],
 [3, 6, 5, 6],
 [4, 5, 5, 7],
 [4, 5, 3, 2],
 [5, 7, 3, 4],
 [7, 6, 2, 6],
 [5, 2, 5, 5],
 [3, 5, 5, 6],
 [5, 5, 5, 4],
 [6, 3, 3, 5],
 [5, 4, 2, 5],
 [6, 2, 6, 5],
 [5, 5, 5, 6],
 [5, 6, 6, 2],
 [6, 4, 5, 7],
 [7, 5, 6, 4],
 [6, 6, 5, 5],
 [4, 3, 5, 5],
 [4, 3, 7, 6],
 [6, 7, 5, 7],
 [6, 3, 4, 5],
 [5, 6, 6, 3],
 [6, 5, 2, 7],
 [2, 5, 5, 3],
 [7, 7, 5, 2],
 [5, 2, 7, 3],
 [2, 3, 2, 6],
 [6, 6, 6, 2],
 [2, 6, 4, 3],
 [3, 3, 6, 6],
 [7, 6, 4,

In [2]:
from pprint import pprint
digits = {  0 : 'abcefg',
            1 : 'cf',
            2 : 'acdeg',
            3 : 'acdfg',
            4 : 'bcdf',
            5 : 'abdfg',
            6 : 'abdefg',
            7 : 'acf',
            8 : 'abcdefg',
            9 : 'abcdfg'}
digits_len = { k:len(digits[k]) for k in digits }
uniq_digits = [1, 4, 7, 8]
uniq_lens =  [digits_len[u] for u in uniq_digits]
uniq_lens

[2, 4, 3, 7]

In [3]:
import numpy as np
x = [[ (sym in uniq_lens) for sym in row ] for row in values]
np.sum(x)



383

# P2


In [55]:
digits = {  0 : 'abcefg',
            1 : 'cf',
            2 : 'acdeg',
            3 : 'acdfg',
            4 : 'bcdf',
            5 : 'abdfg',
            6 : 'abdefg',
            7 : 'acf',
            8 : 'abcdefg',
            9 : 'abcdfg'}
letter2int = { c:ord(c) - ord('a') for c in 'abcdefg'}
digits_list = [ [ letter2int[char] for char in digits[d]] for d in digits]
digits_list
mat = np.zeros((10,7),dtype='int8')
for i,d in enumerate(digits_list):
    for j in d:
        mat[i][j]=1
#print( np.unique(  np.sum(mat,axis=0)), return_counts=True  ) 
print(np.unique(  np.sum(mat,axis=0), return_counts=True  ))
print(np.unique(  np.sum(mat,axis=1), return_counts=True  ))

np.sum(mat,axis=0)


(array([4, 6, 7, 8, 9]), array([1, 1, 2, 2, 1]))
(array([2, 3, 4, 5, 6, 7]), array([1, 1, 1, 3, 3, 1]))


array([8, 6, 8, 7, 4, 9, 7])