In [135]:
import numpy as np
fname = 'input'
lines = open(fname,'r').read()
coord, folds = [ l.split("\n") for l in lines.split("\n\n")]
coord = np.array([ [ int(c) for c in l.split(",")] for l in coord])
n_cols,n_rows = np.amax(coord, axis=0)+1


field = np.zeros((n_rows,n_cols),dtype='int16')
print([size_y,size_x])
field
for dcol, drow in coord:
    field[drow,dcol]=1

def fold(t, direction, idx):
    if direction == 'y':
        lhs = t[0:idx, :]
        rhs = t[idx+1:,:][::-1,:]
        res = (lhs+rhs) 
    elif direction=='x':
        lhs = t[:, 0:idx]
        rhs = t[:, idx+1:][:,::-1]
        res = (lhs+rhs) 
    return res
for sfold in folds:
    print(sfold)
    direction, sidx = sfold.split(" ")[2].split("=")
    idx = int(sidx)
    field = fold(field, direction, idx)
    
field[field>0]=1

ans = np.sum(field)
print(f"Ans : {ans}")
print(field)

[15, 11]
fold along x=655
fold along y=447


ValueError: operands could not be broadcast together with shapes (447,655) (446,655) 

In [102]:
t = np.reshape(np.arange(35),(5,7))


[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
---------
[[ 6  6  6]
 [20 20 20]
 [34 34 34]
 [48 48 48]
 [62 62 62]]


[10, 14]
